name: Bulkheaddesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#281920'
    - '#64574e'
    - '#9c8a74'
    - '#236087'
    - '#fefcd5'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.037807486252859235
purpose: []
