name: Bulkheaddesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff5429'
    - '#406666'
    - '#ff9f87'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.037807486252859235
purpose: []
