name: Bulkheaddesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040600'
    - '#919191'
    - '#ffc800'
    - '#0cafad'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
